# permissions for end users to edit samples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sample-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-autoscaler
    app.kubernetes.io/part-of: kubebuilder-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: sample-editor-role
rules:
- apiGroups:
  - example.com.example.com
  resources:
  - samples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com.example.com
  resources:
  - samples/status
  verbs:
  - get
